#     _    _                 _ _____ _______   __
#    / \  | | __ _  ___ _ __(_)_   _|_   _\ \ / /
#   / _ \ | |/ _` |/ __| '__| | | |   | |  \ V /
#  / ___ \| | (_| | (__| |  | | | |   | |   | |
# /_/   \_\_|\__,_|\___|_|  |_| |_|   |_|   |_|
#
# See this wiki page for more info:
# https://github.com/jwilm/alacritty/wiki

env:
  TERM: xterm-256color

# Window configurations
window:
  dimensions:
    columns: 0
    lines: 0

  padding:
    x: 0
    y: 0

  decorations: full

scrolling:
  multiplier: 1

# Font configurations
font:
  normal:
    family: SauceCodePro Nerd Font
    style: Regular

  bold:
    family: SauceCodePro Nerd Font
    style: Bold

  italic:
    family: SauceCodePro Nerd Font
    style: Italic

  size: 11.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  #scale_with_dpi: true

  use_thin_strokes: false

draw_bold_text_with_bright_colors: true

schemes:
  # Monokai Dark
  monokai-dark: &monokai-dark
    primary:
      background: '0x282a36'
      foreground: '0xf8f8f2'

    normal:
     black:   '0x272822'
     red:     '0xF92672'
     green:   '0xA6E22E'
     yellow:  '0xF4BF75'
     blue:    '0x66D9EF'
     magenta: '0xAE81FF'
     cyan:    '0xA1EFE4'
     white:   '0xF8F8F2'

    bright:
     black:   '0x75715E'
     red:     '0xF92672'
     green:   '0xA6E22E'
     yellow:  '0xF4BF75'
     blue:    '0x66D9EF'
     magenta: '0xAE81FF'
     cyan:    '0xA1EFE4'
     white:   '0xF9F8F5'

  # Tokyo Night theme, based on both:
  #   https://github.com/ghifarit53/tokyonight-vim
  #   https://github.com/enkia/tokyo-night-vscode-theme
  tokyo-night: &tokyo-night
    # Default colors
    primary:
      background: '0x1a1b26'
      foreground: '0xa9b1d6'

    # Normal colors
    normal:
      black:   '0x32344a'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan:    '0x449dab'
      white:   '0x787c99'

    # Bright colors
    bright:
      black:   '0x444b6a'
      red:     '0xff7a93'
      green:   '0xb9f27c'
      yellow:  '0xff9e64'
      blue:    '0x7da6ff'
      magenta: '0xbb9af7'
      cyan:    '0x0db9d7'
      white:   '0xacb0d0'

# Colors (Monokai Dark)
colors: *tokyo-night

# Bell
bell:
  animation: EaseOutExpo
  duration: 0

background_opacity: 1.0

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  faux_scrolling_lines: 1
  hide_when_typing: false

cursor:
  style: Block
  unfocused_hollow: true

dynamic_title: true

live_config_reload: true

key_bindings:
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }
  - { key: Y,        mods: Control, action: Paste                        }
  - { key: W,        mods: Alt,     action: Copy                         }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Plus,      mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  - { key: Return,   mods: Alt,           action: ToggleFullscreen }
  - { key: Paste,                    action: Paste                            }
  - { key: Copy,                     action: Copy                             }
  - { key: L,         mods: Control, action: ClearLogNotice                   }
  - { key: L,         mods: Control, chars: "\x0c"                            }
  - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
  - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }
