- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.config/:
        glob: true
        path: config/*
        force: true
    ~/.xinitrc:
    ~/.Xresources:
    ~/.zprofile:

- create:
    - ~/.images

- shell:
  - [curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | gpg --import -, Adding Spotify GPG Key]
