- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.config/:
        glob: true
        path: config/*
    ~/.gitconfig:
    ~/.oh-my-zsh: ohmyzsh
    ~/.oh-my-zsh/custom:
        path: ohmyzsh-custom
        force: true
    ~/.scripts:
    ~/.xinitrc:
    ~/.zprofile:
    ~/.zshrc:

- create:
    - ~/downloads
    - ~/.images
    - ~/projects
    - ~/.vim/undo-history

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - [curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | gpg --import -, Adding Spotify GPG Key]
