- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.config/bat:
    ~/config/neofetch:
    ~/config/nvim:
    ~/config/ranger:
    ~/.gitconfig:
    ~/.scripts:
    ~/.zshrc:

- create:
    - ~/downloads
    - ~/projects
    - ~/.vim/undo-history

- shell:
  - [git submodule update --init --recursive, Installing submodules]
