- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.config/pam-gnupg: config/pam-gnupg
    ~/.gitconfig:
    ~/.gnupg:
    ~/.oh-my-zsh: ohmyzsh
    ~/.oh-my-zsh-custom:
        path: ohmyzsh-custom
        force: true
    ~/.p10k.zsh:
    ~/.scripts:
    ~/.ssh:
    ~/.zshrc:

- create:
    - ~/bin
    - ~/downloads
    - ~/projects
    - ~/.vim/undo-history

