- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.config/bat: config/bat
    ~/.config/neofetch: config/neofetch
    ~/.config/nvim: config/nvim
    ~/.config/ranger: config/ranger
