- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.config/bat: config/bat
    ~/.config/neofetch: config/neofetch
    ~/.config/nvim: config/nvim
    ~/.config/ranger: config/ranger
    ~/.gitconfig:
    ~/.oh-my-zsh: ohmyzsh
    ~/.oh-my-zsh/custom:
        path: ohmyzsh-custom
        force: true
    ~/.p10k.zsh:
    ~/.scripts:
    ~/.ssh:
    ~/.zshrc:

- create:
    - ~/downloads
    - ~/projects
    - ~/.vim/undo-history