#!/usr/bin/env bash

set -e

HELP="Usage: ./install <operation>
Setup dotfiles and install Arch Linux packages.

operations:
    -p           installs packages

Examples:
$ ./install
$ ./install -p"

packagesFlag=
while getopts p name
do
    case $name in
        p) packagesFlag=1;;
        *) echo "$HELP"
           exit 2;;
    esac
done

CONFIG="install.conf.yaml"
PACKAGES="packages.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}"

if [ "$packagesFlag" ]; then
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${PACKAGES}" --plugin-dir "${BASEDIR}/dotbot-yay"
fi