#!/usr/bin/env bash

set -e

HELP="Usage: ./install <operation>
Setup dotfiles and install Arch Linux packages.

operations:
    -p           installs packages

Examples:
$ ./install
$ ./install -p"

packagesFlag=
while getopts p name
do
    case $name in
        p) packagesFlag=1;;
        *) echo "$HELP"
           exit 2;;
    esac
done

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive

# Initialize all Submodules
git submodule update --init --recursive

# Windows SubSystem Linux
CONFIG_WSL="config_wsl.conf.yaml"
PACKAGES_WSL="packages_wsl.conf.yaml"
if [[ $(uname -r) =~ microsoft ]]; then
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_WSL}"
    if [ "$packagesFlag" ]; then
        "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${PACKAGES_WSL}" --plugin-dir "${BASEDIR}/dotbot-yay"
    fi
fi

# Arch Linux
CONFIG_ARCH="config_arch.conf.yaml"
PACKAGES_ARCH="packages_arch.conf.yaml"
if [[ $(uname -r) =~ arch ]]; then
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_ARCH}"
    if [ "$packagesFlag" ]; then
        "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${PACKAGES_ARCH}" --plugin-dir "${BASEDIR}/dotbot-yay"
    fi
fi