#!/usr/bin/env bash

set -e

HELP="Usage: ./install <operation>
Setup dotfiles and install Arch Linux packages.

operations:
    -p           installs packages

Examples:
$ ./install
$ ./install -p"

packagesFlag=
while getopts p name
do
    case $name in
        p) packagesFlag=1;;
        *) echo "$HELP"
           exit 2;;
    esac
done

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive

# Initialize all Submodules
git submodule update --init --recursive

# Base Config and Packages
CONFIG_BASE="config_base.conf.yaml"
PACKAGES_BASE="packages_base.conf.yaml"
# Windows SubSystem Linux
CONFIG_WSL="config_wsl.conf.yaml"
PACKAGES_WSL="packages_wsl.conf.yaml"
# Arch Linux
CONFIG_ARCH="config_arch.conf.yaml"
PACKAGES_ARCH="packages_arch.conf.yaml"
# VirtualBox
PACKAGES_VIRTUALBOX="packages_virtualbox.conf.yaml"

# If -p flag passed then install everything needed first
# otherwise none of the config will work and git will look
# for SSH keys.
if [ "$packagesFlag" ]; then
    # Base Packages
    echo "BASE: Packages"
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${PACKAGES_BASE}" --plugin-dir "${BASEDIR}/dotbot-yay"

    # WSL Packages
    if [[ $(uname -r) =~ microsoft ]]; then
      echo "WSL: Packages"
      "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${PACKAGES_WSL}" --plugin-dir "${BASEDIR}/dotbot-yay"
    fi

    # Arch Packages
    if [[ $(uname -r) =~ arch ]]; then
      echo "ARCH: Packages"
      "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${PACKAGES_ARCH}" --plugin-dir "${BASEDIR}/dotbot-yay"
    fi

    # VirtualBox Packages
    if grep -q "^flags.*hypervisor" /proc/cpuinfo; then
      echo "VIRT: Packages"
      "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${PACKAGES_VIRTUALBOX}" --plugin-dir "${BASEDIR}/dotbot-yay"
    fi
fi

# Base Config
echo "BASE: Config"
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_BASE}"

# WSL Config
if [[ $(uname -r) =~ microsoft ]]; then
    echo "WSL: Config"
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_WSL}"
fi

# Arch Config
if [[ $(uname -r) =~ arch ]]; then
    echo "ARCH: Config"
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_ARCH}"
fi

# VirtualBox Config
if grep -q "^flags.*hypervisor" /proc/cpuinfo; then
    echo "VIRT: Config"
fi
